/**
 * Map Spanish country names → flag-icons codes (ISO 3166-1 alpha-2,
 * with `gb-eng/gb-sct/gb-wls/gb-nir` for the UK home nations).
 */

const ENTRIES: Array<[string, string]> = [
  ["mexico", "mx"],
  ["estados unidos", "us"],
  ["estados unidos de america", "us"],
  ["usa", "us"],
  ["canada", "ca"],
  ["argentina", "ar"],
  ["brasil", "br"],
  ["uruguay", "uy"],
  ["colombia", "co"],
  ["ecuador", "ec"],
  ["paraguay", "py"],
  ["peru", "pe"],
  ["chile", "cl"],
  ["bolivia", "bo"],
  ["venezuela", "ve"],
  ["costa rica", "cr"],
  ["panama", "pa"],
  ["honduras", "hn"],
  ["el salvador", "sv"],
  ["guatemala", "gt"],
  ["jamaica", "jm"],
  ["haiti", "ht"],
  ["cuba", "cu"],
  ["republica dominicana", "do"],
  ["trinidad y tobago", "tt"],
  ["espana", "es"],
  ["curazao", "cw"],
  ["rd del congo", "cd"],
  ["rdc", "cd"],
  ["francia", "fr"],
  ["alemania", "de"],
  ["italia", "it"],
  ["portugal", "pt"],
  ["paises bajos", "nl"],
  ["holanda", "nl"],
  ["belgica", "be"],
  ["suiza", "ch"],
  ["austria", "at"],
  ["dinamarca", "dk"],
  ["suecia", "se"],
  ["noruega", "no"],
  ["finlandia", "fi"],
  ["islandia", "is"],
  ["irlanda", "ie"],
  ["inglaterra", "gb-eng"],
  ["escocia", "gb-sct"],
  ["gales", "gb-wls"],
  ["irlanda del norte", "gb-nir"],
  ["reino unido", "gb"],
  ["croacia", "hr"],
  ["serbia", "rs"],
  ["polonia", "pl"],
  ["chequia", "cz"],
  ["republica checa", "cz"],
  ["eslovaquia", "sk"],
  ["eslovenia", "si"],
  ["hungria", "hu"],
  ["rumania", "ro"],
  ["bulgaria", "bg"],
  ["grecia", "gr"],
  ["turquia", "tr"],
  ["ucrania", "ua"],
  ["rusia", "ru"],
  ["bielorrusia", "by"],
  ["bosnia y herzegovina", "ba"],
  ["albania", "al"],
  ["macedonia del norte", "mk"],
  ["montenegro", "me"],
  ["kosovo", "xk"],
  ["marruecos", "ma"],
  ["argelia", "dz"],
  ["tunez", "tn"],
  ["egipto", "eg"],
  ["sudafrica", "za"],
  ["senegal", "sn"],
  ["ghana", "gh"],
  ["camerun", "cm"],
  ["costa de marfil", "ci"],
  ["nigeria", "ng"],
  ["mali", "ml"],
  ["burkina faso", "bf"],
  ["cabo verde", "cv"],
  ["congo", "cg"],
  ["republica democratica del congo", "cd"],
  ["angola", "ao"],
  ["mozambique", "mz"],
  ["kenia", "ke"],
  ["etiopia", "et"],
  ["zambia", "zm"],
  ["tanzania", "tz"],
  ["uganda", "ug"],
  ["sudan", "sd"],
  ["mauritania", "mr"],
  ["gabon", "ga"],
  ["guinea ecuatorial", "gq"],
  ["japon", "jp"],
  ["corea del sur", "kr"],
  ["corea del norte", "kp"],
  ["china", "cn"],
  ["india", "in"],
  ["australia", "au"],
  ["nueva zelanda", "nz"],
  ["arabia saudita", "sa"],
  ["arabia saudi", "sa"],
  ["iran", "ir"],
  ["irak", "iq"],
  ["qatar", "qa"],
  ["catar", "qa"],
  ["emiratos arabes unidos", "ae"],
  ["jordania", "jo"],
  ["israel", "il"],
  ["libano", "lb"],
  ["palestina", "ps"],
  ["uzbekistan", "uz"],
  ["kazajistan", "kz"],
  ["tailandia", "th"],
  ["vietnam", "vn"],
  ["filipinas", "ph"],
  ["malasia", "my"],
  ["indonesia", "id"],
];

function normalize(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

const MAP = new Map(ENTRIES);

export function countryCode(name: string): string | null {
  return MAP.get(normalize(name)) ?? null;
}
